spring:
  datasource:
   url: jdbc:mysql://47.107.127.220:3306/security?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
   username: root
   password: mayuzhu521.QCZ
   driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: none

server:
  port: 8090
security:
#  oauth2:
#    client:
#      clientId: imooc
#      clientSecret: imoocsecret
  basic:
    enabled: false

management:
  security:
    enabled: false

boot:
  browser:
    token-validity-seconds: 72000

