spring:
  datasource:
   url: jdbc:mysql://47.107.127.220:3306/security?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
   username: root
   password: mayuzhu521.QCZ
   driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: none
  redis:
#    sentinel:
#      master: 47.107.127.220
#      nodes:
    host: 47.107.127.220
    port: 6380
    password: qcz0816
    database: 0
    timeout: 0
    pool:
      max-active: 8
      max-wait:  -1
      max-idle: 500
      min-idle: 0
#    cluster:
#      nodes: 47.107.127.220:6379
#      max-redirects: 1

server:
  port: 8090

security:
#  oauth2:
#    client:
#      clientId: imooc
#      clientSecret: imoocsecret
  basic:
    enabled: false

management:
  security:
    enabled: false

boot:
  browser:
    token-validity-seconds: 72000
  app:
    oauth2:
      token-store: jwt

